version: '3.4'
services:
  ndexbase:
    build:
      context: .
      dockerfile: Dockerfile
    restart: "always"
    user: 'root'
    volumes:
      - ./main.R:/home/main.R
    command: "/usr/bin/Rscript /home/main.R"
    ports:
      - "80:8787"
